name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install dependencies
        uses: dart-lang/setup-dart@v1.3

      - run: dart pub get
      - run: dart pub upgrade
      
      - run: touch tests.json
    
      - run: dart test
        
      # - run: python test/conftest.py 

      # - name: Natijalar
      #   run: |
      #     CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
      #     echo $CHANGED_FILES
      #     python test/sendtest.py ${{github.actor}} '${{github.repository}}' "$CHANGED_FILES"
